### ISSUE TITLE
【bug反馈】创建房间直传时，二维码数量不断增加

### ISSUE THREAD

**Issue by 8mv** [IvanHanloth/Easy-Send#17]
创建房间直传时，二维码数量不断增加

**Comment by IvanHanloth** [comment]
你好，感谢您的反馈，该问题已经定位，将在最新的更新中修复该问题，敬请关注

**Comment by IvanHanloth** [comment]
问题修复已提交至仓库，仅涉及public/template/room/js/default.js文件。在456行后插入`$("#room_qrcode").html('');`即可。
由于修改较少，此问题不再单独进行后台更新推送，可自行修复或下载最新版release进行覆盖修复
