### ISSUE TITLE
安装部署后无法正常访问

### ISSUE THREAD

**Issue by Mrgongm** [IvanHanloth/Easy-Send#19]
首页提示：
“Warning: Undefined array key "mode" in /www/wwwroot/send.mrgongm.cn/index.php on line 25”
“Warning: Undefined array key "mode" in /www/wwwroot/send.mrgongm.cn/index.php on line 31”
“Warning: Undefined array key "key" in /www/wwwroot/send.mrgongm.cn/theme/blue/index/index.php on line 85”
“Warning: Undefined array key "roomid" in /www/wwwroot/send.mrgongm.cn/theme/blue/index/index.php on line 92”

https://域名/user 一直显示加载动画

请问是配置问题吗

**Comment by IvanHanloth** [comment]
你好，这个问题主要是由于作者偷懒少写了判断所访问的键值是否存在导致。
会出现于php8.0以上的版本，可以参考一下解决方案:
1.在会出现提示的页面中添加error_reporting(0); 或修改php.ini
2.将php版本回退为7.3
我们也将在近期的更新中对该问题修复，感谢您的反馈。

**Comment by IvanHanloth** [comment]
页面持续加载的原因是使用的翻译接口访问时间过长，该问题也将在最新的版本中修复，预计今晚推送

**Comment by Mrgongm** [comment]
已解决，赞！୧(๑•̀◡•́๑)૭
