### ISSUE TITLE
建议提取验证码改为纯数字或者不区分大小写

### ISSUE THREAD

**Issue by zhufacai** [IvanHanloth/Easy-Send#3]
经常要手动输入，纯数字或者不区分大小写会比较方便一点，另外如果可以在线更新就很完美了

**Comment by zhufacai** [comment]
https://github.com/shuyudao/wenchuan这个模板挺好看，能新增个模板吗？

**Comment by zhufacai** [comment]
https://github.com/shuyudao/wenchuan 
这个模板挺好看，能新增个模板吗？

**Comment by IvanHanloth** [comment]
关于提取码:
大小写混合的设计主要考虑到数据的安全性问题，您可通过以下方式优化体验
1.扫描二维码进行文件提取
2.修改"common.php"中第16行，将"random"函数中变量$chars修改为"abcdefghijklmnopqrstuvwxyz"即可
3.修改"function/save_text.php"第20行及"function/upload_file.php"第30行中，"random(4)"修改为 random(4,"abcdefghijklmnopqrstuvwxyz")即可（如果需要为纯数字则改为random(4,"num")）

**Comment by IvanHanloth** [comment]
关于提取码:
大小写混合的设计主要考虑到数据的安全性问题，您可通过以下方式优化体验
1.扫描二维码进行文件提取
2.修改"common.php"中第16行，将"random"函数中变量$chars修改为"abcdefghijklmnopqrstuvwxyz"即可
3.修改"function/save_text.php"第20行及"function/upload_file.php"第30行中，"random(4)"修改为 random(4,"abcdefghijklmnopqrstuvwxyz")即可（如果需要为纯数字则改为random(4,"num")）

**Comment by IvanHanloth** [comment]
关于在线更新:
此功能可能将在Easy-Send v3.0中添加，敬请关注

**Comment by IvanHanloth** [comment]
关于模板:
此模板将在近期更新(Easy-Send v2.2.2)中加入，敬请期待
