### ISSUE TITLE
管理员账号密码无法登录

### ISSUE THREAD

**Issue by jxzzlfh** [IvanHanloth/Easy-Send#7]
主域名/admin，进入登录界面，输入admin和123456，无法登录，显示账号或密码错误

**Comment by IvanHanloth** [comment]
请进入数据库“setting”表格，将name为account的行对应的content值修改为admin，将name为password的行对应的content值修改为ODdkOWJiNDAwYzA2MzQ2OTFmMGUzYmFhZjFlMmZkMGQ=
或您可直接执行以下SQL指令
UPDATE `setting` SET `content` = 'ODdkOWJiNDAwYzA2MzQ2OTFmMGUzYmFhZjFlMmZkMGQ=' WHERE `name` = 'password';
UPDATE `setting` SET `content` = 'admin' WHERE `name` = 'account';

**Comment by jxzzlfh** [comment]
按照上述方法，已解决管理员登录问题
